cask_args appdir: "/Applications"
tap "homebrew/cask"
tap "homebrew/cask-fonts"

brew "git"
brew "zsh"
brew "vim"
brew "tmux"
brew "z"
brew "tree"
brew "openssl"
brew "diff-so-fancy"
brew "nvm"
brew "dnsmasq"
brew "jq"
brew "fzf"
brew "ripgrep"
brew "fastlane"
brew "svn"
brew "font-source-code-pro"

cask "iterm2"
cask "spotify"
cask "docker"
cask "visual-studio-code"
cask "alfred"
cask "dash"
cask "paw"
cask "firefox"
cask "tuple"
cask "devutils"
cask "font-sauce-code-pro-nerd-font"
